### ISSUE TITLE
ImportError: cannot import name cli

### ISSUE THREAD

**Issue by Ryan-Holben** [IvanMalison/okcupyd#79] opened 2016-01-23 04:37 UTC
When simply running 'import okcupyd', I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Happycake/anaconda2/envs/OKC-dev/lib/python2.7/site-packages/okcupyd/__init__.py", line 5, in <module>
    from invoke import cli as invoke
ImportError: cannot import name cli
```

My pip freeze is:
```
appnope==0.1.0
coloredlogs==5.0
decorator==4.0.6
gnureadline==6.3.3
humanfriendly==1.43.1
invoke==0.12.0
ipython==4.0.3
ipython-genutils==0.1.0
lxml==3.5.0
okcupyd==1.0.0a3
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5
requests==2.9.1
simplegeneric==0.8.1
simplejson==3.8.1
six==1.10.0
SQLAlchemy==1.0.11
traitlets==4.1.0
wheel==0.26.0
wrapt==1.10.6
```
I tried this with the non-alpha version of okcupyd as well.

**Comment by ThreeCorners** [comment] 2016-01-23 05:43
Nevermind, it just exists in the alpha version, and commenting out fixes it!

**Comment by IvanMalison** [comment] 2016-01-23 19:18
no this is real issue, the problem is that invoke changed its import structure. The solution is to just remove the import.

**Comment by kingyakshaver** [comment] 2016-06-29 03:55
hmm this sucks. Whats the ETA?

**Comment by Ryan-Holben** [comment] 2016-06-29 04:13
I don't think it's been changed since I mentioned it last, but again, easy fix; just comment out that import.

**Comment by IvanMalison** [comment] 2016-06-29 04:21
yep, actually, I think that Invoke finally has the functionality that I had hoped for, so we can make the okcupyd binary just call out to it and use all of its tasks

**Comment by A5HRAJ** [comment] 2016-07-11 07:36
I commented out `from invoke import cli as invoke` to fix the error, but now I get a different issue:

`Traceback (most recent call last):
  File "/usr/local/bin/okcupyd", line 7, in <module>
    from okcupyd import interactive
  File "/usr/local/lib/python2.7/site-packages/okcupyd/__init__.py", line 8, in <module>
    from . import tasks
  File "/usr/local/lib/python2.7/site-packages/okcupyd/tasks/__init__.py", line 7, in <module>
    from . import db as db_collection
  File "/usr/local/lib/python2.7/site-packages/okcupyd/tasks/db.py", line 15, in <module>
    @task(default=True)
  File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 303, in inner
    autoprint=autoprint,
  File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!`

**Comment by IvanMalison** [comment] 2016-07-11 17:15
yeah, I have a fix for this.

**Closed** 2016-07-13 15:15 UTC
