### ISSUE TITLE
Error: ImportError: cannot import name ColoredStreamHandler

### ISSUE THREAD

**Issue by scientist7** [IvanMalison/okcupyd#75] opened 2015-12-22 00:25 UTC
Hi,

After a:
  
    pip install okcupyd==1.0.0a2

When I do:

    import okcupyd

I get this error:
    Traceback (most recent call last):

    File "<ipython-input-1-6450ba7d2558>", line 1, in <module>
    import okcupyd

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\__init__.py", line 9, in <module>
    from . import tasks

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\tasks\__init__.py", line 6, in <module>
    from . import copy

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\tasks\copy.py", line 6, in <module>
    from okcupyd.user import User

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\user.py", line 6, in <module>
    from . import helpers

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\helpers.py", line 11, in <module>
    from .xpath import xpb

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\xpath.py", line 1, in <module>
    from .util import cached_property

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\util\__init__.py", line 13, in <module>
    from .misc import *

    File "C:\Users\Ben\Anaconda2\lib\site-packages\okcupyd\util\misc.py", line 8, in <module>
    from coloredlogs import ColoredStreamHandler

    ImportError: cannot import name ColoredStreamHandler

I tried pip install coloredlogs --upgrade, but it didn't help.

Thanks!

**Comment by IvanMalison** [comment] 2015-12-22 02:30
Caused by:

https://github.com/xolox/python-coloredlogs/commit/52f6dd0f2fe8b4a5fac874e3925b75f2c511dd80

Should be fixed by pinning coloredlogs for now, but we should probably move to the new interface.

**Comment by IvanMalison** [comment] 2015-12-25 18:55
This should be fixed. Can you verify?

**Closed by IvanMalison** 2015-12-25 18:55 UTC

**Comment by scientist7** [comment] 2015-12-25 21:08
That works.  Thank you!
